version: '3.5'

services:
  nginx:
    container_name: nginx_tedbirler
    build:
      context: .
      dockerfile: dockerfile_nginx
    ports:
      - 10.10.10.1:9095:80
    depends_on:
      - django
    restart: unless-stopped

  django:
    container_name: django_tedbirler
    build:
      context: .
      dockerfile: dockerfile_django
    volumes:
      - /opt/tedbirler.sqlite3:/app/db.sqlite3
    restart: unless-stopped

