# Generated by Django 4.1.7 on 2023-06-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=1000)),
                ('title_name_az', models.CharField(max_length=1000, null=True)),
                ('title_name_en', models.CharField(max_length=1000, null=True)),
                ('title_name_ru', models.CharField(max_length=1000, null=True)),
                ('title', models.TextField()),
                ('title_az', models.TextField(null=True)),
                ('title_en', models.TextField(null=True)),
                ('title_ru', models.TextField(null=True)),
                ('date', models.DateField(blank=True)),
                ('date_detail', models.CharField(max_length=2000)),
                ('date_detail_az', models.CharField(max_length=2000, null=True)),
                ('date_detail_en', models.CharField(max_length=2000, null=True)),
                ('date_detail_ru', models.CharField(max_length=2000, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('description_az', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Şəkillər',
                'verbose_name_plural': 'Şəkillər',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=2000)),
                ('date', models.DateField(blank=True)),
                ('date_detail', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'verbose_name': 'Videolar',
                'verbose_name_plural': 'Videolar',
            },
        ),
    ]
