# Generated by Django 4.1.7 on 2023-06-02 19:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('title_az', models.CharField(max_length=1000, null=True)),
                ('title_en', models.CharField(max_length=1000, null=True)),
                ('title_ru', models.CharField(max_length=1000, null=True)),
                ('time', models.CharField(max_length=2000)),
                ('description', ckeditor.fields.RichTextField()),
                ('description_az', ckeditor.fields.RichTextField(null=True)),
                ('description_en', ckeditor.fields.RichTextField(null=True)),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
            ],
            options={
                'verbose_name': 'Program Tarixləri',
                'verbose_name_plural': 'Program Tarixləri',
            },
        ),
        migrations.CreateModel(
            name='Event_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('title_az', models.CharField(max_length=1000, null=True)),
                ('title_en', models.CharField(max_length=1000, null=True)),
                ('title_ru', models.CharField(max_length=1000, null=True)),
                ('time', models.CharField(max_length=2000)),
                ('description', ckeditor.fields.RichTextField()),
                ('description_az', ckeditor.fields.RichTextField(null=True)),
                ('description_en', ckeditor.fields.RichTextField(null=True)),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
            ],
            options={
                'verbose_name': 'Program Sxema ',
                'verbose_name_plural': 'Program Sxema ',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.TextField()),
                ('name_az', models.TextField(null=True)),
                ('name_en', models.TextField(null=True)),
                ('name_ru', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_az', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Rektorlar',
                'verbose_name_plural': 'Rektorlar',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('name_az', models.CharField(max_length=1000, null=True)),
                ('name_en', models.CharField(max_length=1000, null=True)),
                ('name_ru', models.CharField(max_length=1000, null=True)),
                ('title', models.CharField(max_length=2000)),
                ('title_az', models.CharField(max_length=2000, null=True)),
                ('title_en', models.CharField(max_length=2000, null=True)),
                ('title_ru', models.CharField(max_length=2000, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('description_az', ckeditor.fields.RichTextField(null=True)),
                ('description_en', ckeditor.fields.RichTextField(null=True)),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Program',
            },
        ),
    ]
