# Generated by Django 4.1.7 on 2023-06-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_event_title_alter_event_title_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name_az',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name_ru',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
