# Generated by Django 4.1.7 on 2023-06-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Komite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menue_name', models.CharField(max_length=1000)),
                ('menue_name_az', models.CharField(max_length=1000, null=True)),
                ('menue_name_en', models.CharField(max_length=1000, null=True)),
                ('menue_name_ru', models.CharField(max_length=1000, null=True)),
                ('name', models.CharField(max_length=2000)),
                ('name_az', models.CharField(max_length=2000, null=True)),
                ('name_en', models.CharField(max_length=2000, null=True)),
                ('name_ru', models.CharField(max_length=2000, null=True)),
                ('profile', models.ImageField(upload_to='images/')),
                ('about', models.TextField()),
                ('about_az', models.TextField(null=True)),
                ('about_en', models.TextField(null=True)),
                ('about_ru', models.TextField(null=True)),
                ('social1', models.CharField(max_length=1000)),
                ('social2', models.CharField(max_length=1000)),
                ('social3', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Komitə 1',
                'verbose_name_plural': 'Komitə 1',
            },
        ),
        migrations.CreateModel(
            name='Komite_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menue_name', models.CharField(max_length=1000)),
                ('menue_name_az', models.CharField(max_length=1000, null=True)),
                ('menue_name_en', models.CharField(max_length=1000, null=True)),
                ('menue_name_ru', models.CharField(max_length=1000, null=True)),
                ('name', models.CharField(max_length=2000)),
                ('name_az', models.CharField(max_length=2000, null=True)),
                ('name_en', models.CharField(max_length=2000, null=True)),
                ('name_ru', models.CharField(max_length=2000, null=True)),
                ('profile', models.ImageField(upload_to='images/')),
                ('about', models.TextField()),
                ('about_az', models.TextField(null=True)),
                ('about_en', models.TextField(null=True)),
                ('about_ru', models.TextField(null=True)),
                ('social1', models.CharField(max_length=1000)),
                ('social2', models.CharField(max_length=1000)),
                ('social3', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Komitə 2',
                'verbose_name_plural': 'Komitə 2',
            },
        ),
    ]
