# Generated by Django 4.1.7 on 2023-06-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_news_name_alter_news_name_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainphoto',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='mainphoto',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name_az',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name_en',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name_ru',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
