# Generated by Django 4.1.7 on 2023-06-02 19:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xaber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000)),
                ('name_az', models.CharField(max_length=3000, null=True)),
                ('name_en', models.CharField(max_length=3000, null=True)),
                ('name_ru', models.CharField(max_length=3000, null=True)),
                ('title', models.TextField()),
                ('title_az', models.TextField(null=True)),
                ('title_en', models.TextField(null=True)),
                ('title_ru', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateField(blank=True)),
                ('description', tinymce.models.HTMLField()),
                ('description_az', tinymce.models.HTMLField(null=True)),
                ('description_en', tinymce.models.HTMLField(null=True)),
                ('description_ru', tinymce.models.HTMLField(null=True)),
            ],
            options={
                'verbose_name': 'XƏBƏRLƏR',
                'verbose_name_plural': 'XƏBƏRLƏR',
            },
        ),
    ]
