# Generated by Django 4.1.7 on 2023-06-02 19:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('name_az', models.CharField(blank=True, max_length=2000, null=True)),
                ('name_en', models.CharField(blank=True, max_length=2000, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('main_description', tinymce.models.HTMLField()),
                ('main_description_az', tinymce.models.HTMLField(null=True)),
                ('main_description_en', tinymce.models.HTMLField(null=True)),
                ('main_description_ru', tinymce.models.HTMLField(null=True)),
                ('sub_description1', tinymce.models.HTMLField()),
                ('sub_description1_az', tinymce.models.HTMLField(null=True)),
                ('sub_description1_en', tinymce.models.HTMLField(null=True)),
                ('sub_description1_ru', tinymce.models.HTMLField(null=True)),
                ('sub_description2', tinymce.models.HTMLField()),
                ('sub_description2_az', tinymce.models.HTMLField(null=True)),
                ('sub_description2_en', tinymce.models.HTMLField(null=True)),
                ('sub_description2_ru', tinymce.models.HTMLField(null=True)),
                ('sub_description3', tinymce.models.HTMLField()),
                ('sub_description3_az', tinymce.models.HTMLField(null=True)),
                ('sub_description3_en', tinymce.models.HTMLField(null=True)),
                ('sub_description3_ru', tinymce.models.HTMLField(null=True)),
            ],
            options={
                'verbose_name': 'Haqqımda',
                'verbose_name_plural': 'Haqqımda',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000)),
                ('name_az', models.CharField(max_length=3000, null=True)),
                ('name_en', models.CharField(max_length=3000, null=True)),
                ('name_ru', models.CharField(max_length=3000, null=True)),
                ('profile', models.ImageField(upload_to='images/')),
                ('about', models.TextField()),
                ('about_az', models.TextField(null=True)),
                ('about_en', models.TextField(null=True)),
                ('about_ru', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Şəxslər',
                'verbose_name_plural': 'Şəxslər',
            },
        ),
    ]
